try {
    const a = 1 + 1
    const b = a * 5
    console.log(b);
} catch (error) {
    console.log(error);
}
